---
# This playbook records the output of 'racadm getsysinfo' for each
# system in the idrac host group into files in the sysinfo directory.
- hosts: idrac
  tasks:
    - name: get system info
      raw: racadm getsysinfo
      register: sysinfo

    - name: ensure output directory exists
      delegate_to: localhost
      file:
        path: ./sysinfo
        state: directory

    - name: write system info to a file
      delegate_to: localhost
      copy:
        content: "{{ sysinfo.stdout }}"
        dest: "./sysinfo/{{ inventory_hostname }}.txt"
